### ISSUE TITLE
Model steps to increase.

### ISSUE THREAD

**Issue by kashif7009** [ngzhian/multi-step-modal#11]
how to increase model steps in this model box .currently there are three steps in the model but we need six steps how to make this?

**Comment by ngzhian** [comment]
Check out the example on the [README](https://github.com/ngzhian/multi-step-modal/blob/master/README.md), what you have to do is to create the new HTML elements with the appropriate classes and attributes, e.g.

```
<h4 class="modal-title step-4" data-step="4">Step 4</h4>
<h4 class="modal-title step-5" data-step="5">Step 5</h4>
<h4 class="modal-title step-6" data-step="6">Step 6</h4>
```
