### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by Terkura** [ngzhian/multi-step-modal#12]
I will suggest instead of the ff lines in updating the progress bar
var $buttons = $modal.find('button.step');
var total_num_steps = $buttons.length;
the following lines should be used 
var $div_total = $modal.find('div[data-step]');
var total_num_steps = $div_total.length;
this will give a more accurate reflection of the 
total_num_steps variable irrespective the number of buttons added to reflect user needs

**Comment by ngzhian** [comment]
Hi, I'm not maintaining this library anymore, would you like to submit a PR? Thanks :)

**Comment by Terkura** [comment]
Sorry, but what do you mean by a PR?

On Oct 28, 2017 4:40 PM, "Ng Zhi An" <notifications@github.com> wrote:

Hi, I'm not maintaining this library anymore, would you like to submit a
PR? Thanks :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ngzhian/multi-step-modal/issues/12#issuecomment-340199869>,
or mute the thread

**Comment by ngzhian** [comment]
A PR is a [Pull Request](https://help.github.com/articles/about-pull-requests/)

**Comment by Terkura** [comment]
Ah! My bad!! I'm really struggling to get my head around git, but hey if
it's for the greater good of the code, I'll sure want to submit a PR

**Comment by ngzhian** [comment]
No worries :) Totally not urgent nor required, but if you would like to get some practice with git/github. Lmk if you face any problems!

**Comment by Terkura** [comment]
Thanks mate!

**Comment by newradius** [comment]
You could merge this PR https://github.com/ngzhian/multi-step-modal/pull/4 which already solves the problem.

**Comment by ngzhian** [comment]
thanks for brining it up @newradius , in this case @Terkura , you can refer to #4 for an implementation. Or actually my comment in that PR still stands, can you remove the class `step` from back buttons so that they don't add to the count? If that solves the problem then no code change is needed :)

**Comment by newradius** [comment]
@ngzhian maybe you should include it in the readme or just merge it for a correct behaviour. You can merge it with 1 click since there isn't any conflict.

**Comment by ngzhian** [comment]
Yea good idea to include in the README, I think a fix will be better. Unfortunately I can't merged it with one click because the PR's original repo has been deleted :/

**Comment by newradius** [comment]
@ngzhian I can send a new PR if you want.

**Comment by ngzhian** [comment]
More than happy to accept a PR if you want this change in :)

**Comment by newradius** [comment]
@ngzhian ready https://github.com/ngzhian/multi-step-modal/pull/13

**Comment by ngzhian** [comment]
Merged! Thanks for your help @newradius :) @Terkura see if this fixes your issue
