### ISSUE TITLE
any plan on bs4?

### ISSUE THREAD

**Issue by juniorxxue** [ngzhian/multi-step-modal#15]
Not an issue, just ask some questions.
lately I am working on a project on bs4 and I need this functionality. Can you be kind to offer some suggestions? And sorry for taking your time. Thanks

**Comment by ngzhian** [comment]
I havent been following bs4 dev at all, does this plug-in "just work" with
bs4? Otherwise I think just changing the class names to match the modal
class names in bs4 should work.
