### ISSUE TITLE
Scroll top popup

### ISSUE THREAD

**Issue by kingfisher11** [ngzhian/multi-step-modal#18]
how to modify the code to scroll to top for each modal if the content of modal content is long?

**Comment by ngzhian** [comment]
Hm, won't the modal be already scrolled to the top by default?
Do you want to scroll to the top when the modal is first opened? You can probably do `$('.modal-body').scrollTop(0)`?

**Comment by kingfisher11** [comment]
First modal is on top. If the second modal have long content, it will appear to the bottom of the page. Where do i place the code? Inside html or js?

**Comment by ngzhian** [comment]
Probably, anywhere you want, such as in the JS, in the onClick listener for second modal.
If you have an example showing what you're talking about, please share it.

**Comment by kingfisher11** [comment]
I am not sure where the exact location to place the code. Can you show me? I am using your code and did not modify it. Thank you

**Comment by ngzhian** [comment]
Here, https://github.com/ngzhian/multi-step-modal/blob/master/index.html#L32
instead of `onclick="sendEvent('#demo-modal-1', 2)"`
something like `onclick="sendEventAndScrollToTop('#demo-modal-1', 2)"`
then
```
function sendEventAndScrollToTop(sel, ev) {
  sendEvent(sel, ev);
  $(".modal .step-2").scrollTop(0);
}
```

**Comment by kingfisher11** [comment]
Is it not working..idk why

here is my code:
`<button type="button" class="btn myButton step step-1" data-step="1" onclick="sendEventAndScrollToTop('#demo-modal-3', 2)">Continue</button>
				<button type="button" class="btn myButton step step-2" data-step="2" onclick="sendEventAndScrollToTop('#demo-modal-3', 1)">Back</button>
				<button type="button" class="btn myButton step step-2" data-step="2" onclick="sendEventAndScrollToTop('#demo-modal-3', 3)">Continue</button>
                <button type="button" class="btn myButton step step-3" data-step="3" onclick="sendEventAndScrollToTop('#demo-modal-3', 2)">Back</button>
				<button type="button" class="btn myButton step step-3" data-step="3" onclick="sendEventAndScrollToTop('#demo-modal-3', 4)">Continue</button>
                <button type="button" class="btn myButton step step-4" data-step="4" onclick="sendEventAndScrollToTop('#demo-modal-3', 3)">Back</button>
				<button type="button" class="btn myButton step step-4" data-step="4" onclick="sendEventAndScrollToTop('#demo-modal-3', 5)">Continue</button>
                <button type="button" class="btn myButton step step-5" data-step="5" onclick="sendEventAndScrollToTop('#demo-modal-3', 4)">Back</button>
				<button type="button" class="btn myButton step step-5" data-step="5" onclick="sendEventAndScrollToTop('#demo-modal-3', 6)">Continue</button>
                <button type="button" class="btn myButton step step-6" data-step="6" onclick="sendEventAndScrollToTop('#demo-modal-3', 5)">Back</button>
				<button type="button" class="btn myButton step step-6" data-step="6" onclick="sendEventAndScrollToTop('#demo-modal-3', 7)">Continue</button>
                <button type="button" class="btn myButton step step-7" data-step="7" onclick="sendEventAndScrollToTop('#demo-modal-3', 6)">Back</button>
				<button type="button" class="btn myButton step step-7" data-step="7" onclick="sendEventAndScrollToTop('#demo-modal-3', 8)">Continue</button>
                <button type="button" class="btn myButton step step-8" data-step="8" onclick="sendEventAndScrollToTop('#demo-modal-3', 7)">Back</button>
				<button type="button" class="btn myButton step step-8" data-step="8" onclick="sendEventAndScrollToTop('#demo-modal-3', 9)">Continue</button>
                <button type="button" class="btn myButton step step-9" data-step="9" onclick="sendEventAndScrollToTop('#demo-modal-3', 8)">Back</button>
				<button type="button" class="btn myButton step step-9" data-step="9" onclick="sendEventAndScrollToTop('#demo-modal-3', 10)">Continue</button>
                <button type="button" class="btn myButton step step-10" data-step="10" onclick="sendEventAndScrollToTop('#demo-modal-3', 9)">Back</button>`

and this is the js:
`<script>
sendEvent = function(sel, step) {
    var sel_event = new CustomEvent('next.m.' + step, {detail: {step: step}});
    window.dispatchEvent(sel_event);
}

function sendEventAndScrollToTop(sel, ev) {
  sendEvent(sel, ev);
  $(".modal .step-2").scrollTop(0);
}
</script>`

the scrollTop should be on modal step 2

**Comment by ngzhian** [comment]
Oh, okay. Change `$(".modal .step-2").scrollTop(0);` to `$("form.modal").scrollTop(0);`. I misunderstood what you meant by the modal being at the bottom. Lmk if this fixes things.

**Comment by kingfisher11** [comment]
OMG! That solved my problem..Thanks mate!

**Comment by ngzhian** [comment]
Sure thing. Do you know how to use [Chrome DevTools](https://developers.google.com/web/tools/chrome-devtools)? I used it to figure out which element was scrolled to the bottom, saw that it was the entire modal form element, and changed the JS to scroll it instead of the modal body. Maybe that will be helpful for you in the future.
