### ISSUE TITLE
multi steps not modal

### ISSUE THREAD

**Issue by skynet** [ngzhian/multi-step-modal#2]
Would it be possible to use it here: http://bootsnipp.com/snippets/featured/form-process-steps

**Comment by ngzhian** [comment]
@skynet if you mean whether we can use it outside of a modal, then no, currently this only supports modals.

If you mean whether we can have that kind of styling for the progress, then yea it's possible, you can either modify the function `updateProgress`, that's where the progress bar is updated. Or you can bind a event listener to the modal (relevant code that does something similar [here](https://github.com/ngzhian/multi-step-modal/blob/master/multi-step-modal.js#L94).
Sorry I don't have much capacity to support this right now, so would appreciate any pull request to improve this, thanks! :)

**Comment by skynet** [comment]
:+1:
