### ISSUE TITLE
Opening modal with only JS

### ISSUE THREAD

**Issue by chackerian** [ngzhian/multi-step-modal#5]
Would it be possible to open a modal with only JS and no **data-toggle** or **data-target** attributes?

**Comment by chackerian** [comment]
So I realized that the modals have their style display attributes changed to block when activated so I used `$(".MYIDHERE").attr("style", "display: block");` to display. 

The issue that remains is, the background doesn't fade like it usually does. How can I get the background to fade when I'm manually triggering the modal.

**Comment by ngzhian** [comment]
Hi, this is related to bootstrap's modal, you can follow these instructions to get hte modal to show up with the fade effect http://getbootstrap.com/javascript/#modalshow
Note that you also need to have the `fade` class on the modal.

**Comment by chackerian** [comment]
That makes sense. I forgot multi-modal was using bootstrap. Thanks.
