### ISSUE TITLE
<a> in modals

### ISSUE THREAD

**Issue by chackerian** [ngzhian/multi-step-modal#6]
I want to use <a> tags to redirect the user to a NON Modal page when clicked. The issue with this is the modals never get closed so there remains the darkened background when the page goes to the link.

**Comment by ngzhian** [comment]
From what I see it could be because you're using meteor, and `<a>` tags don't reload a page, so the modal stays, you can call `$('#myModal').modal('hide')` to hide it ([docs](http://getbootstrap.com/javascript/#modalhide))

**Comment by chackerian** [comment]
Ok. I was curious if there was any other way but that works.
