### ISSUE TITLE
How to reset step on close popup

### ISSUE THREAD

**Issue by hashmab** [ngzhian/multi-step-modal#8]
Hi 

How to reset step on close popup?

Thanks

**Comment by hashmab** [comment]
I have resolve myself. Please use add line 

$modal.on('hidden.bs.modal', function () {
                reset();
                updateProgress(1, total_num_steps); /// add thies line to reset to step 1.
                $modal.find('.step-1').show();
            })

**Comment by ngzhian** [comment]
Thanks for your suggestion. This isn't something I would want to support for this library, as some users might want to preserve the progress of the step. However I have added a note to the README, so users who want this feature can look at this issue for your example code!

**Comment by guibranco** [comment]
This can be added as an option of the plugin, disabled by default, if the user wants this behavior, then he need to pass "autoReset: true" to the constructor...

**Comment by ngzhian** [comment]
Thanks for your suggestion @guibranco, if you would like this feature I am happy to take a PR :)
