### ISSUE TITLE
Does this work with Gravity multistep forms?

### ISSUE THREAD

**Issue by HandHugs** [ngzhian/multi-step-modal#9]
I am trying to find something that will work with gravity multistep forms. Can anyone post an example?

**Comment by ngzhian** [comment]
@HandHugs I don't know what's gravity multistep forms, mind sharing a link? This library is meant to be used quite independently, so the answer is probably no.

**Comment by HandHugs** [comment]
Gravity forms is a huge plugin for WordPress and other sites that allows people to build their own forms. http://www.gravityforms.com/features/form-builder/
